version: '3.7'

services:
  db:
    image: postgres:11.18-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    #volumes:
      #- ./data/postgres:/var/lib/postgresql/data
      #- ./db_init/:/docker-entrypoint-initdb.d

